name: browserdetect-dart
description: A small script to detect certain browsers (rewritten in Dart)
version: 0.1.3

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
